server:
  port: 9101

spring:
  datasource:
    url: jdbc:mysql://localhost:3401/db_pedido?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka

spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:41092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

app:
  kafka:
    topics:
      orden-eventos: orden-eventos

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.upeu.pedido: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
